export const links = [
  { name: 'covidfightclub.org' },
  { name: 'coronaresources.in' },
  { name: 'covid19-twitter.in' },
  { name: 'external.sprinklr.com' },
  { name: 'factchecker.in' },
  { name: 'covidresource.glideapp.io' },
  { name: 'thejasonsamuel.com/fightcovid' },
  { name: 'covid-resources-chi.versel.app' },
  { name: 'plasmadonor.in' },
  { name: 'covidfacts.in' },
  { name: 'needplasma.in' },
  { name: 'plasmaline.in' },
  { name: 'covidhelpgroup.org' },
  { name: 'covidhelpers.co.in' },
  { name: 'indiaplasmadonor.com' },
  { name: 'dhoondh.com' },
  { name: 'stopcorona.tn.gov.in/beds.php' },
  { name: 'covidresourcesindia.com' },
  { name: 'covidhelpsite.carred.co' },
  { name: 'hydcovidresources.com' },
  { name: 'yogesharma.com/covid-dhule/' },
  { name: 'covidamd.com' },
  { name: 'covidtools.in' },
  { name: 'covid19helpindia.in' },
  { name: 'app.covid19relief' },
];
